esphome:
  name: realdash
  includes:
   - realdashino.h
  
esp32:
  board: esp32-c3-devkitm-1
  variant: esp32c3 
    
#logger:
#  level: DEBUG

ota:
  platform: esphome
  password: !secret otaxywfpow

web_server:
  port: 9005

 
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: !secret xywfpow_IP
    gateway: !secret gateway
    subnet: !secret subnet

captive_portal:

custom_component:
- lambda: |-
    auto my_custom = new MyCustomComponent();
    return {my_custom};
  components:
  - id: my_custom_id
