esphome:
  name: realdash
external_components:
  - source: github://creepystefan/realdash-esphome
  
esp32:
  board: esp32-c3-devkitm-1
  variant: esp32c3 
    
logger:
  
ota:
  platform: esphome
  password: !secret otaxywfpow

web_server:
  port: 9005

 
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  
captive_portal:

realdash:
  - platform: frame44
    can_id: 0x1
    #Automatical creat Data_ID
    #  (CAN_ID & DATA1)   (example 0x1data1)    
    #  (CAN_ID & DATA2)                     4 byte to serial to realdash
    #  (CAN_ID & DATA3)
    #  (CAN_ID & DATA4)
  - platform: frame44
    can_id: 0x2
    #  (CAN_ID & DATA1)   (example 0x2data1)    
    #  (CAN_ID & DATA2)   
    #  (CAN_ID & DATA3)
    #  (CAN_ID & DATA4)

    

sensor:
  - platform: ....
    id: 0x1data1
  - platform: ....
    id: 0x1data2
  - platform: ....
    id: 0x2data1

