esphome:
  name: fauxmoesp
  
  
esp32:
  board: esp32-c3-devkitm-1
  variant: esp32c3 
    
logger:
  level: DEBUG

ota:
  platform: esphome
  password: !secret otaxywfpow

web_server:
  port: 9005

esp32_ble_server:
  
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: !secret xywfpow_IP
    gateway: !secret gateway
    subnet: !secret subnet
 
captive_portal:


#RealDash CAN '44' frame:
#4 bytes - 0x44,0x33,0x22,0x11

canbus:
  - platform: esp32_can
    tx_pin: GPIO21
    rx_pin: GPIO20
    can_id: 0
    use_extended_id: false
    bit_rate: 125kbps
       

interval:
  - interval: 1s
    then:
      - canbus.send:
          data: [ 0x44, 0x33, 0x22, 0x11, 0x00, 0x00, 0x01, 0x02, 0x01,0x02,0x03,0x04,0x05,0x06,0x07,0x08 ]
          use_extended_id: false
          can_id: 0

 
